overwrite: true
schema:
  - "schema/schema.graphql"
documents:
  - "schema/query.graphql"
generates:
  backend/src/generated/graphql.ts:
    documents: null
    plugins:
      - "typescript"
      - "typescript-resolvers"
    config:
      # avoidOptionals: true
      useIndexSignature: true
  frontend/src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withComponent: false
      withHOC: false
      withHooks: true
      apolloReactCommonImportFrom: "@apollo/client"
      apolloReactHooksImportFrom: "@apollo/client"
  frontend/src/generated/fragmentTypes.json:
    plugins:
      - fragment-matcher
